{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ include "youlend.namespace" . }}
  labels:
    {{- include "youlend.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    {{- include "youlend.backend.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.targetPort }}
    protocol: TCP
  sessionAffinity: None
{{- end }}
